export const ENDGAME_LESSONS = [
  {
    id: 'kp-vs-k',
    name: 'חייל בודד מול מלך',
    icon: '♙',
    description: 'למדו את טכניקת ה"אופוזיציה" - הובילו את המלך שלכם לפני החייל כדי להבטיח הכתרה.',
    fen: '8/8/8/3k4/3P4/3K4/8/8 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 600,
    objective: 'win',
  },
  {
    id: 'kr-vs-k',
    name: 'מט בצריח בודד',
    icon: '♖',
    description: 'דחקו את המלך היריב לשפת הלוח בעזרת הצריח והמלך שלכם, ותנו מט.',
    fen: '8/8/8/4k3/8/8/4K3/4R3 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 400,
    objective: 'win',
  },
  {
    id: 'kq-vs-k',
    name: 'מט במלכה בודדת',
    icon: '♕',
    description: 'תנו מט עם המלכה בעזרת המלך שלכם - זהירות שלא לתת פט!',
    fen: '8/8/8/4k3/8/8/4K3/4Q3 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 400,
    objective: 'win',
  },
  {
    id: 'two-rooks-vs-k',
    name: 'מט "מדרגות" בשני צריחים',
    icon: '♜♜',
    description: 'הזיזו את הצריחים לסירוגין כדי לדחוק את המלך היריב לשורה הראשונה ולתת מט.',
    fen: '8/8/8/4k3/8/R6R/1K6/8 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 400,
    objective: 'win',
  },
  {
    id: 'two-bishops-vs-k',
    name: 'מט בשני רצים',
    icon: '♝♝',
    description: 'תרגול מתקדם - דחקו את המלך היריב לפינה בעזרת שני הרצים והמלך שלכם.',
    fen: '8/8/8/4k3/8/8/4K3/2B2B2 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 400,
    objective: 'win',
  },
  {
    id: 'r-vs-p',
    name: 'הגנה: צריח מול חייל',
    icon: '🛡️',
    description: 'החייל היריב קרוב להכתרה - השתמשו במלך ובצריח כדי לעצור אותו ולהשיג לפחות תיקו.',
    fen: '8/8/8/8/8/2k5/2p5/R4K2 w - - 0 1',
    studentColor: 'w',
    difficultyElo: 800,
    objective: 'not-lose',
  },
];
